/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.CCWC.CCWC;

import picocli.CommandLine;

public class App {
	public static void main(String[] args) {
		new CommandLine(new CCWC()).execute(args);
	}
}
